language: node_js
node_js:
  - '10'
  - '12'
  - '14'
install:
  - yarn
script: yarn check && yarn test
after_success:
- travis_retry yarn test --coverage && node_modules/.bin/coveralls < coverage/lcov.info